codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        informational: false
    patch:
      default:
        informational: false

ignore:
  - "javafx-app/src/main/java/com/uiptv/ui/**"
  - "javafx-app/src/main/java/com/uiptv/player/**"
  - "javafx-app/src/main/java/com/uiptv/widget/**"
  - "javafx-app/src/main/java/com/uiptv/player/api/VideoPlayerInterface.java"
  - "javafx-app/src/main/java/com/uiptv/ui/util/ColoredStatusTableCell.java"
  - "javafx-app/src/main/java/com/uiptv/ui/util/ImageCacheManager.java"
  - "javafx-app/src/main/java/com/uiptv/ui/util/StyleClassDecorator.java"
  - "website/**"
